// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: block.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (block_name, geometry_type, coordinates, color, card_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, block_name, geometry_type, coordinates, metadata, created_at, card_id, color
`

type CreateBlockParams struct {
	BlockName    string      `json:"block_name"`
	GeometryType string      `json:"geometry_type"`
	Coordinates  []byte      `json:"coordinates"`
	Color        pgtype.Text `json:"color"`
	CardID       pgtype.UUID `json:"card_id"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.BlockName,
		arg.GeometryType,
		arg.Coordinates,
		arg.Color,
		arg.CardID,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.BlockName,
		&i.GeometryType,
		&i.Coordinates,
		&i.Metadata,
		&i.CreatedAt,
		&i.CardID,
		&i.Color,
	)
	return i, err
}

const deleteBlockByID = `-- name: DeleteBlockByID :exec
DELETE FROM blocks WHERE id = $1
`

func (q *Queries) DeleteBlockByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlockByID, id)
	return err
}

const deleteBlocksByCardName = `-- name: DeleteBlocksByCardName :exec
DELETE FROM blocks USING cards WHERE blocks.card_id = cards.id AND cards.card_name = $1
`

func (q *Queries) DeleteBlocksByCardName(ctx context.Context, cardName string) error {
	_, err := q.db.Exec(ctx, deleteBlocksByCardName, cardName)
	return err
}

const listBlocks = `-- name: ListBlocks :many
SELECT id, block_name, geometry_type, coordinates, metadata, created_at, card_id, color FROM blocks
`

func (q *Queries) ListBlocks(ctx context.Context) ([]Block, error) {
	rows, err := q.db.Query(ctx, listBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.BlockName,
			&i.GeometryType,
			&i.Coordinates,
			&i.Metadata,
			&i.CreatedAt,
			&i.CardID,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
