// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card.sql

package db

import (
	"context"
)

const listCards = `-- name: ListCards :many
SELECT id, card_name, description, created_at, zoom_level, center_coordinates, color FROM cards
`

func (q *Queries) ListCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.Query(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.CardName,
			&i.Description,
			&i.CreatedAt,
			&i.ZoomLevel,
			&i.CenterCoordinates,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
