// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conductor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConductor = `-- name: CreateConductor :one
INSERT INTO conductors (
    full_name
) VALUES (
    $1
) RETURNING id
`

func (q *Queries) CreateConductor(ctx context.Context, fullName string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createConductor, fullName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getConductorByName = `-- name: GetConductorByName :one
SELECT id FROM conductors
WHERE full_name ILIKE $1 LIMIT 1
`

func (q *Queries) GetConductorByName(ctx context.Context, fullName string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getConductorByName, fullName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listConductors = `-- name: ListConductors :many
SELECT id, user_id, full_name, created_at FROM conductors
ORDER BY full_name ASC
`

func (q *Queries) ListConductors(ctx context.Context) ([]Conductor, error) {
	rows, err := q.db.Query(ctx, listConductors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conductor{}
	for rows.Next() {
		var i Conductor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
