// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ID           pgtype.UUID        `json:"id"`
	BlockName    string             `json:"block_name"`
	GeometryType string             `json:"geometry_type"`
	Coordinates  []byte             `json:"coordinates"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CardID       pgtype.UUID        `json:"card_id"`
	Color        pgtype.Text        `json:"color"`
}

type Card struct {
	ID                pgtype.UUID        `json:"id"`
	CardName          string             `json:"card_name"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ZoomLevel         pgtype.Int4        `json:"zoom_level"`
	CenterCoordinates []byte             `json:"center_coordinates"`
	Color             pgtype.Text        `json:"color"`
}

type Conductor struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FullName  string             `json:"full_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID        pgtype.UUID        `json:"id"`
	EventType string             `json:"event_type"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ScheduleEntry struct {
	ID              pgtype.UUID        `json:"id"`
	ScheduleDate    pgtype.Date        `json:"schedule_date"`
	StartTime       pgtype.Time        `json:"start_time"`
	TaskDescription string             `json:"task_description"`
	ConductorID     pgtype.UUID        `json:"conductor_id"`
	VenueID         pgtype.UUID        `json:"venue_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ScheduleEntryBlock struct {
	ScheduleEntryID pgtype.UUID `json:"schedule_entry_id"`
	BlockID         pgtype.UUID `json:"block_id"`
	EntrySubgroupID pgtype.UUID `json:"entry_subgroup_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Venue struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Location       pgtype.Text        `json:"location"`
	IsRotationPool bool               `json:"is_rotation_pool"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
