// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateConductor(ctx context.Context, fullName string) (pgtype.UUID, error)
	CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (ScheduleEntry, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (pgtype.UUID, error)
	DeleteScheduleEntriesByDateRange(ctx context.Context, arg DeleteScheduleEntriesByDateRangeParams) error
	GetConductorByName(ctx context.Context, fullName string) (pgtype.UUID, error)
	GetVenueByName(ctx context.Context, name string) (pgtype.UUID, error)
	ListConductors(ctx context.Context) ([]Conductor, error)
	ListScheduleEntries(ctx context.Context, arg ListScheduleEntriesParams) ([]ScheduleEntry, error)
	// -- name: GetScheduleConductorByName :one
	// SELECT id FROM conductors
	// WHERE full_name ILIKE $1 LIMIT 1;
	// -- name: CreateScheduleConductor :one
	// INSERT INTO conductors (
	//     full_name
	// ) VALUES (
	//     $1
	// ) RETURNING id;
	ListUniqueTaskDescriptions(ctx context.Context) ([]string, error)
	ListVenues(ctx context.Context) ([]Venue, error)
}

var _ Querier = (*Queries)(nil)
