// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
	CreateConductor(ctx context.Context, fullName string) (pgtype.UUID, error)
	CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (ScheduleEntry, error)
	CreateVenue(ctx context.Context, arg CreateVenueParams) (pgtype.UUID, error)
	DeleteBlockByID(ctx context.Context, blockName string) error
	DeleteBlocksByCardName(ctx context.Context, cardName string) error
	DeleteScheduleEntriesByDateRange(ctx context.Context, arg DeleteScheduleEntriesByDateRangeParams) error
	GetConductorByName(ctx context.Context, fullName string) (pgtype.UUID, error)
	GetOrCreateCard(ctx context.Context, cardName string) (Card, error)
	GetVenueByName(ctx context.Context, name string) (pgtype.UUID, error)
	ListBlocks(ctx context.Context) ([]Block, error)
	ListCards(ctx context.Context) ([]Card, error)
	ListConductors(ctx context.Context) ([]Conductor, error)
	ListScheduleEntries(ctx context.Context, arg ListScheduleEntriesParams) ([]ScheduleEntry, error)
	// -- name: CreateBlock :one
	// INSERT INTO blocks (
	//     block_name, geometry_type, coordinates, card_id
	// ) VALUES (
	//     $1, $2, $3, $4
	// ) RETURNING *;
	ListUniqueTaskDescriptions(ctx context.Context) ([]string, error)
	ListVenues(ctx context.Context) ([]Venue, error)
}

var _ Querier = (*Queries)(nil)
