// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduleEntry = `-- name: CreateScheduleEntry :one
INSERT INTO schedule_entries (
    schedule_date, start_time, task_description, conductor_id, venue_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, schedule_date, start_time, task_description, conductor_id, venue_id, created_at
`

type CreateScheduleEntryParams struct {
	ScheduleDate    pgtype.Date `json:"schedule_date"`
	StartTime       pgtype.Time `json:"start_time"`
	TaskDescription string      `json:"task_description"`
	ConductorID     pgtype.UUID `json:"conductor_id"`
	VenueID         pgtype.UUID `json:"venue_id"`
}

func (q *Queries) CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (ScheduleEntry, error) {
	row := q.db.QueryRow(ctx, createScheduleEntry,
		arg.ScheduleDate,
		arg.StartTime,
		arg.TaskDescription,
		arg.ConductorID,
		arg.VenueID,
	)
	var i ScheduleEntry
	err := row.Scan(
		&i.ID,
		&i.ScheduleDate,
		&i.StartTime,
		&i.TaskDescription,
		&i.ConductorID,
		&i.VenueID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScheduleEntriesByDateRange = `-- name: DeleteScheduleEntriesByDateRange :exec
DELETE FROM schedule_entries
WHERE schedule_date >= $1 AND schedule_date <= $2
`

type DeleteScheduleEntriesByDateRangeParams struct {
	ScheduleDate   pgtype.Date `json:"schedule_date"`
	ScheduleDate_2 pgtype.Date `json:"schedule_date_2"`
}

func (q *Queries) DeleteScheduleEntriesByDateRange(ctx context.Context, arg DeleteScheduleEntriesByDateRangeParams) error {
	_, err := q.db.Exec(ctx, deleteScheduleEntriesByDateRange, arg.ScheduleDate, arg.ScheduleDate_2)
	return err
}

const listScheduleEntries = `-- name: ListScheduleEntries :many
SELECT id, schedule_date, start_time, task_description, conductor_id, venue_id, created_at FROM schedule_entries
WHERE schedule_date >= $1 
  AND schedule_date <= $2
ORDER BY schedule_date ASC, start_time ASC
`

type ListScheduleEntriesParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) ListScheduleEntries(ctx context.Context, arg ListScheduleEntriesParams) ([]ScheduleEntry, error) {
	rows, err := q.db.Query(ctx, listScheduleEntries, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleEntry{}
	for rows.Next() {
		var i ScheduleEntry
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleDate,
			&i.StartTime,
			&i.TaskDescription,
			&i.ConductorID,
			&i.VenueID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniqueTaskDescriptions = `-- name: ListUniqueTaskDescriptions :many


SELECT DISTINCT task_description FROM schedule_entries
ORDER BY task_description ASC
`

// -- name: GetScheduleConductorByName :one
// SELECT id FROM conductors
// WHERE full_name ILIKE $1 LIMIT 1;
// -- name: CreateScheduleConductor :one
// INSERT INTO conductors (
//
//	full_name
//
// ) VALUES (
//
//	$1
//
// ) RETURNING id;
func (q *Queries) ListUniqueTaskDescriptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUniqueTaskDescriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var task_description string
		if err := rows.Scan(&task_description); err != nil {
			return nil, err
		}
		items = append(items, task_description)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
