// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (
    name,
    location
) VALUES (
    $1, $2
) RETURNING id
`

type CreateVenueParams struct {
	Name     string      `json:"name"`
	Location pgtype.Text `json:"location"`
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVenue, arg.Name, arg.Location)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getVenueByName = `-- name: GetVenueByName :one
SELECT id FROM venues
WHERE name ILIKE $1 LIMIT 1
`

func (q *Queries) GetVenueByName(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getVenueByName, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listVenues = `-- name: ListVenues :many
SELECT id, name, location, is_rotation_pool, created_at FROM venues
ORDER BY name ASC
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.Query(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venue{}
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.IsRotationPool,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
