// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/conductors": {
            "get": {
                "description": "Get a list of all conductors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "conductors"
                ],
                "summary": "List conductors",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Conductor"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        },
        "/maps/blocks": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "List user-defined blocks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Block"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "Create a new user-defined block",
                "parameters": [
                    {
                        "description": "Block creation request",
                        "name": "block",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateBlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Block"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        },
        "/maps/blocks/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "Upload a CSV file to sync blocks",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file with block data",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        },
        "/maps/cards": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "List user-defined cards (placeholder)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Card"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        },
        "/maps/generated-blocks": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "map"
                ],
                "summary": "List generated blocks in Lekki Phase 1",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MapBlocksResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules": {
            "get": {
                "description": "Get a list of schedule entries for a given date range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "List schedule entries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date in YYYY-MM-DD format",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date in YYYY-MM-DD format",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ScheduleEntry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a schedule entry for a specified date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Create a schedule entry",
                "parameters": [
                    {
                        "description": "Schedule entry details",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleEntry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/:id": {
            "put": {
                "description": "Update an existing schedule entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Update a schedule entry",
                "parameters": [
                    {
                        "description": "Schedule entry details",
                        "name": "default",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateScheduleEntryParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScheduleEntry"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/upload": {
            "post": {
                "description": "Upload a PDF file to sync schedule entries. Optionally specify a year to filter the entries.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "Upload a schedule PDF",
                "parameters": [
                    {
                        "type": "file",
                        "description": "PDF file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Optional year to filter entries (e.g., 2026)",
                        "name": "year",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.BasicErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.BasicErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "default": "An error occurred"
                }
            }
        },
        "handlers.BasicSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "default": "Operation successful"
                }
            }
        },
        "handlers.CreateEntryRequest": {
            "type": "object",
            "required": [
                "schedule_date",
                "start_time",
                "task_description"
            ],
            "properties": {
                "schedule_date": {
                    "description": "Expecting YYYY-MM-DD",
                    "type": "string",
                    "default": "YYYY-MM-DD"
                },
                "start_time": {
                    "description": "Expecting HH:MM:SS",
                    "type": "string",
                    "default": "HH:MM:SS"
                },
                "task_description": {
                    "description": "Expecting \"task description\"",
                    "type": "string",
                    "default": "task description"
                }
            }
        },
        "models.Block": {
            "type": "object",
            "properties": {
                "card_id": {
                    "description": "Optional association to a card, can be null",
                    "type": "string"
                },
                "coordinates": {
                    "description": "For Polygon and LineString: [[lon, lat], [lon, lat], ...]",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "format": "float64"
                        }
                    }
                },
                "geometry_type": {
                    "description": "\"Polygon\" or \"LineString\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Card": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Conductor": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.CreateBlockRequest": {
            "type": "object",
            "required": [
                "coordinates",
                "geometry_type",
                "name"
            ],
            "properties": {
                "coordinates": {
                    "description": "Expecting array of [lon, lat] pairs",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "number",
                            "format": "float64"
                        }
                    }
                },
                "geometry_type": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.MapBlocksResponse": {
            "type": "object",
            "properties": {
                "blocks_count": {
                    "type": "integer"
                },
                "polygons": {
                    "description": "Nested array: [Polygon][Point][Lat/Lon]",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number",
                                "format": "float64"
                            }
                        }
                    }
                }
            }
        },
        "models.ScheduleEntry": {
            "type": "object",
            "properties": {
                "card_id": {
                    "type": "string"
                },
                "conductor_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "schedule_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "task_description": {
                    "type": "string"
                }
            }
        },
        "models.UpdateScheduleEntryParams": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "schedule_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "task_description": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
